/**
 * ========================================
 * COPILOTO IA - DATA
 * Banco de dados centralizado (Mock)
 * ========================================
 */

// Configuração de Tenants (Multi-tenant)
const TENANTS = {
    'default': {
        name: 'Kiko Bim Imóveis',
        primaryColor: '#d4af37',
        secondaryColor: '#1e293b',
        logoText: 'KB',
        logoUrl: 'logos/logo-kiko.png',
        slug: 'kiko-bim'
    },
    'investt': {
        name: 'Investt Imóveis',
        primaryColor: '#3b82f6',
        secondaryColor: '#eff6ff',
        logoText: 'logos/logo-investt.png',
        slug: 'investt' 
    },
    'lux': {
        name: 'Lux Properties',
        primaryColor: '#10b981',
        secondaryColor: '#ecfdf5',
        logoText: 'LP',
        slug: 'lux'
    },
    'imob': {
        name: 'Imobiliária Premium',
        primaryColor: '#ef4444',
        secondaryColor: '#fef2f2',
        logoText: 'IP',
        slug: 'imob'
    }
};

// Dados de atendimentos
const atendimentosData = [
    { created_at: "2026-02-03 18:00:40.094+00", telefone: "11986458562", nome: "Maria Silva", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "Apartamento 2 quartos", valor_buscado: 2500, temperatura: "morno", resumo: "Cliente interessado em locação, discutindo valores de aluguel, condomínio e IPTU. Ajustes finais em negociação ainda em andamento.", fup_pendente: false, etapa_funil: "contato" },
    { created_at: "2026-02-03 18:00:49.682+00", telefone: "11999295476", nome: "João Santos", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "A imobiliária enviou comunicado ao inquilino sobre proibição de festas e barulho no apartamento. O cliente não manifestou interesse em buscar imóvel.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:00:55.474+00", telefone: "13955493094", nome: "Ana Paula", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "muito_quente", resumo: "Cliente já está na fase final do processo, enviou contrato assinado e documentos necessários, confirmou pagamento. Planeja buscar as chaves pessoalmente.", fup_pendente: false, etapa_funil: "fechamento" },
    { created_at: "2026-02-03 18:01:03.595+00", telefone: "14996250907", nome: "Carlos Oliveira", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Conversa apenas sobre comunicado de regras de convivência no apartamento, sem interesse declarado em busca de imóvel.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:01:09.804+00", telefone: "14997306200", nome: "Fernanda Lima", busca_imovel: true, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "apartamento 254", valor_buscado: 0, temperatura: "frio", resumo: "Cliente interessado em apartamento 254, ainda não respondeu sobre visita.", fup_pendente: true, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:01:19.464+00", telefone: "17981685594", nome: "Ricardo Souza", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente recebeu informações sobre documentos para garantia fiador na locação, sem buscar imóvel.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:01:25.044+00", telefone: "17988069072", nome: "Patrícia Costa", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente informado sobre transferência de contas do imóvel para inquilino, sem interesse manifestado em buscar imóvel.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:01:31.511+00", telefone: "17988190257", nome: "Marcos Almeida", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "kitnet para locação na região da Minas Gerais", valor_buscado: 800, temperatura: "morno", resumo: "Cliente busca kitnet para locação na região da Minas Gerais. Cliente perguntou sobre envio de documentação digital.", fup_pendente: false, etapa_funil: "contato" },
    { created_at: "2026-02-03 18:01:40.433+00", telefone: "17988263130", nome: "Juliana Martins", busca_imovel: true, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "casa na rua Santa Catarina, Boa Vista", valor_buscado: 0, temperatura: "frio", resumo: "Cliente perguntou sobre a disponibilidade de uma casa na rua Santa Catarina, Boa Vista. Imóvel indisponível.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:01:45.12+00", telefone: "17988299391", nome: "Roberto Ferreira", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Mensagem automática enviada pela empresa informando os contatos para venda, compra ou simulações de financiamentos.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:01:50.027+00", telefone: "17988360405", nome: "Camila Rocha", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente foi orientado a contactar o setor de vistorias com Eric pelo telefone para resolver uma solicitação.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:01:55.355+00", telefone: "17988429861", nome: "Bruno Pereira", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "Imóvel para aluguel com 3 quartos", valor_buscado: 3500, temperatura: "morno", resumo: "Cliente perguntou sobre disponibilidade de imóvel para aluguel com 3 quartos. Informado que o imóvel está disponível.", fup_pendente: true, etapa_funil: "contato" },
    { created_at: "2026-02-03 18:02:01.258+00", telefone: "17991229791", nome: "Luciana Dias", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente não está buscando imóvel, pois o diálogo é sobre a devolução das chaves e comunicação com ex-locatário.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:02:08.137+00", telefone: "17991390757", nome: "Gabriel Mendes", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "morno", resumo: "Cliente enviou o endereço do imóvel e confirmou os dados do contrato. Escolheu assinatura digital e aguarda análise.", fup_pendente: true, etapa_funil: "proposta" },
    { created_at: "2026-02-03 18:02:13.317+00", telefone: "17991427174", nome: "Amanda Costa", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente enviou apenas uma saudação inicial, sem indicar interesse por imóveis.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:00:06.822+00", telefone: "11952704573", nome: "Pedro Henrique", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Início da conversa com um cumprimento, sem informações sobre interesse em imóveis.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:00:13.426+00", telefone: "11965726471", nome: "Isabela Santos", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "Não especificado, mas busca imóvel para locação", valor_buscado: 2000, temperatura: "morna", resumo: "Cliente busca imóvel para locação, informado sobre tipos de garantia e condições de contrato mínimo de 12 meses.", fup_pendente: true, etapa_funil: "contato" },
    { created_at: "2026-02-03 18:00:24.206+00", telefone: "11972272373", nome: "Thiago Oliveira", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente solicita contato do locatário da casa alugada para possível visita de um interessado em compra para investimento.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:00:29.337+00", telefone: "11982060803", nome: "Larissa Lima", busca_imovel: true, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente perguntou o número da casa na Rua Progresso, sendo informado o número 256. Conversa em estágio inicial.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:00:35.955+00", telefone: "11983037613", nome: "Felipe Costa", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "O cliente não manifestou interesse ou busca por imóvel nas conversas.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:01:00.083+00", telefone: "13997943267", nome: "Mariana Souza", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente confirmou ser proprietário no condomínio Terra Verde, mas não manifestou interesse em buscar imóvel.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:00:00.8+00", telefone: "11941848852", nome: "Daniel Almeida", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente confirma que o contrato enviado é o normal e aguarda a versão digital para a assinatura do avô.", fup_pendente: false, etapa_funil: "proposta" },
    { created_at: "2026-02-03 18:01:15.236+00", telefone: "17981630595", nome: "Bianca Martins", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "casas para alugar com 3 quartos", valor_buscado: 3000, temperatura: "frio", resumo: "Cliente perguntou sobre casas para alugar com 3 quartos. Empresa confirmou a existência e enviou link para consulta.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:02:43.364+00", telefone: "17992081334", nome: "Eduardo Pereira", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente interessado em vender seu imóvel, sem interesse em comprar ou alugar. Empresa orientou sobre venda e financiamento.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:02:49.259+00", telefone: "17992235342", nome: "Carolina Rocha", busca_imovel: false, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "casa para locação", valor_buscado: 2500, temperatura: "morno", resumo: "Cliente quer colocar uma casa para locação. Está aguardando os inquilinos saírem para entregar as chaves à imobiliária.", fup_pendente: true, etapa_funil: "contato" },
    { created_at: "2026-02-03 18:03:02.283+00", telefone: "17996008257", nome: "Vinícius Dias", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "muito_frio", resumo: "Conversa focada em liberação de acesso e horário, sem demonstração de interesse em imóvel.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:03:07.709+00", telefone: "17996178367", nome: "Natália Mendes", busca_imovel: true, busca_locacao: false, busca_compra: true, caracteristicas_imovel: "Casa com portão preto em bairro próximo à rodoviaria", valor_buscado: 450000, temperatura: "morno", resumo: "Cliente busca casa com portão preto próximo à rodoviaria, Santa Helena. Imóvel consultado indisponível.", fup_pendente: true, etapa_funil: "contato" },
    { created_at: "2026-02-03 18:03:13.095+00", telefone: "17996179401", nome: "Gustavo Lima", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "imóvel para locação na Sergipe, cliente negocia valor", valor_buscado: 1900, temperatura: "morno", resumo: "Cliente está negociando o valor do aluguel do imóvel na Sergipe, solicitando ajuste para R$1900 devido ao IPTU.", fup_pendente: true, etapa_funil: "proposta" },
    { created_at: "2026-02-03 18:03:22.665+00", telefone: "17996213459", nome: "Letícia Costa", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Conversa inicial sem definição clara de interesse do cliente. Empresa enviou link genérico de imóveis para aluguel.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:03:27.837+00", telefone: "17996279489", nome: "André Souza", busca_imovel: true, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "casa no residencial Santo Afonso", valor_buscado: 0, temperatura: "frio", resumo: "Cliente está coletando informações sobre uma casa no residencial Santo Afonso que está em desocupação e precisa de reparos.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:03:32.016+00", telefone: "17996321051", nome: "Priscila Almeida", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente solicita incluir cláusula no contrato para preservação da Jabuticabeira, sem poda drástica.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:03:36.748+00", telefone: "17996329670", nome: "Leonardo Martins", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente solicitou catálogo de imóveis para locação, está em estágio inicial de busca, sem características ou orçamento definidos.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:03:42.529+00", telefone: "17996331103", nome: "Fernanda Rocha", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente apenas solicitou telefone da Patrícia, não demonstrou interesse em imóveis ou negociação.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:03:49.107+00", telefone: "17996339309", nome: "Matheus Pereira", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "muito_quente", resumo: "Cliente está no estágio de fechamento e já efetuou parte do pagamento da entrada. Comunicação sobre vistoria e acesso ao imóvel confirmadas.", fup_pendente: false, etapa_funil: "fechamento" },
    { created_at: "2026-02-03 18:03:55.136+00", telefone: "17996361123", nome: "Julia Costa", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente relata problemas com reparos do imóvel e aquecedor queimado. Imobiliária enviou contrato para análise.", fup_pendente: true, etapa_funil: "contato" },
    { created_at: "2026-02-03 18:04:01.706+00", telefone: "17996361288", nome: "Rafael Souza", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "casa para aluguel com 3 quartos", valor_buscado: 3200, temperatura: "frio", resumo: "Cliente forneceu endereço sem especificar interesse claro inicialmente, depois recebeu link de uma casa com 3 quartos para aluguel.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:04:07.805+00", telefone: "17996374894", nome: "Beatriz Lima", busca_imovel: true, busca_locacao: false, busca_compra: true, caracteristicas_imovel: "casa com 2 quartos e varanda gourmet", valor_buscado: 380000, temperatura: "morno", resumo: "Cliente demonstrou interesse em uma casa específica à venda com 2 quartos e varanda gourmet.", fup_pendente: true, etapa_funil: "visita" },
    { created_at: "2026-02-03 18:04:18.353+00", telefone: "17996459844", nome: "Lucas Almeida", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "casa de fundos no centro", valor_buscado: 1800, temperatura: "morno", resumo: "Cliente demonstrou interesse em visitar uma casa de fundos no centro. Informações sobre endereço e horário foram fornecidas.", fup_pendente: true, etapa_funil: "visita" },
    { created_at: "2026-02-03 18:04:23.955+00", telefone: "17996519940", nome: "Sofia Martins", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Conversa centrada no reparo da loja, sem menção a interesse em imóveis.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:02:22.315+00", telefone: "17991603212", nome: "Henrique Dias", busca_imovel: true, busca_locacao: false, busca_compra: true, caracteristicas_imovel: "2 dormitórios", valor_buscado: 280000, temperatura: "morno", resumo: "Cliente interessado em imóvel com 2 dormitórios. Empresa informa que há apenas 2 apartamentos disponíveis com essa característica.", fup_pendente: false, etapa_funil: "contato" },
    { created_at: "2026-02-03 18:02:27.14+00", telefone: "17991849107", nome: "Valentina Rocha", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "casa para alugar", valor_buscado: 2200, temperatura: "morno", resumo: "O cliente demonstrou interesse em alugar uma casa e solicitou informações sobre documentos e garantias locatícias.", fup_pendente: true, etapa_funil: "contato" },
    { created_at: "2026-02-03 18:02:31.254+00", telefone: "17991870331", nome: "Enzo Pereira", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "O cliente iniciou contato buscando imóveis para alugar. A empresa enviou um link com opções para aluguel.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:02:34.563+00", telefone: "17991980352", nome: "Lívia Costa", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "O cliente inicialmente demonstrou interesse em locação e estava providenciando documentos para análise.", fup_pendente: false, etapa_funil: "contato" },
    { created_at: "2026-02-03 18:02:39.132+00", telefone: "17991997230", nome: "Guilherme Souza", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Conversa sobre pagamento de contas e contrato. Cliente informou sobre vistoria realizada e necessidade de procedimento.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:04:12.844+00", telefone: "17996413723", nome: "Manuela Lima", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente interessado em locação de casa, recebeu opções por link, mas não definiu características ou valores.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:05:11.151+00", telefone: "17997097461", nome: "Arthur Almeida", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "apartamento ou casa próximo ao centro", valor_buscado: 2000, temperatura: "morno", resumo: "Cliente busca imóvel para alugar, preferencialmente apartamento ou casa próximo ao centro. Imóvel inicialmente consultado não está disponível.", fup_pendente: false, etapa_funil: "contato" },
    { created_at: "2026-02-03 18:05:23.282+00", telefone: "17997151851", nome: "Helena Martins", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente não recebeu o link para fazer a biometria facial via SMS e a empresa reenviou o link via chat.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:05:27.731+00", telefone: "17997167776", nome: "Samuel Rocha", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente iniciou contato, mas não especificou interesse em imóveis nem características desejadas.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:05:37.593+00", telefone: "17997224130", nome: "Clara Costa", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 1500, temperatura: "frio", resumo: "Cliente busca imóvel para alugar, porém o valor do imóvel informado está fora do orçamento dela.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:05:50.974+00", telefone: "17997249269", nome: "Davi Souza", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "Imóvel para alugar, valor R$600,00 mais IPTU", valor_buscado: 600, temperatura: "morno", resumo: "Cliente apenas se identificou inicialmente sem demonstrar interesse, mas depois manifestou interesse em alugar um imóvel por R$600,00 mais IPTU.", fup_pendente: false, etapa_funil: "contato" },
    { created_at: "2026-02-03 18:05:57.565+00", telefone: "17997260441", nome: "Júlia Pereira", busca_imovel: true, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "morno", resumo: "Cliente manifestou interesse inicial em imóvel, porém sem detalhar características ou valores específicos.", fup_pendente: true, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:06:07.543+00", telefone: "17997316449", nome: "Heitor Lima", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente relata problema com a caixinha do interfone externo e já realizou consertos por conta própria.", fup_pendente: true, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:06:13.534+00", telefone: "17997351038", nome: "Alice Martins", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "apartamento para aluguel", valor_buscado: 1200, temperatura: "muito_quente", resumo: "Cliente interessado em fechar o aluguel de um apartamento por R$1200, aguardando envio dos valores do condomínio e IPTU.", fup_pendente: true, etapa_funil: "proposta" },
    { created_at: "2026-02-03 18:06:19.71+00", telefone: "17997382593", nome: "Bernardo Souza", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "casas e apartamentos, incluindo imóvel com 3 quartos", valor_buscado: 0, temperatura: "frio", resumo: "O cliente está buscando imóvel para alugar, foram enviadas opções de casas e apartamentos, inclusive um imóvel específico com 3 quartos.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:06:24.339+00", telefone: "17997384411", nome: "Cecília Costa", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente solicitou ajuda sem especificar interesse por imóvel. Empresa indicou contato para financiamento habitacional.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:06:28.671+00", telefone: "17997389115", nome: "Daniel Lima", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "kitnet ou casa menor para aluguel", valor_buscado: 900, temperatura: "frio", resumo: "Cliente busca kitnet ou casa menor para aluguel. Cliente está em fase inicial de pesquisa, com interesse em imóveis para locação.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:06:33.597+00", telefone: "17997389973", nome: "Eloá Pereira", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "casa para locação", valor_buscado: 1200, temperatura: "frio", resumo: "Cliente busca casas para locação com valor máximo de 1200. Foi enviado um link para imóveis, mas o cliente relata problema ao navegar.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:06:42.702+00", telefone: "17997434594", nome: "Felipe Rocha", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "casas para alugar", valor_buscado: 0, temperatura: "morno", resumo: "Cliente demonstra interesse em casas para alugar e pergunta sobre disponibilidade. Empresa fornece link com opções disponíveis.", fup_pendente: false, etapa_funil: "contato" },
    { created_at: "2026-02-03 18:06:53.627+00", telefone: "17997475948", nome: "Isis Souza", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "casa código 1431 em Santo Afonso", valor_buscado: 2800, temperatura: "morno", resumo: "O cliente está interessado na locação da casa código 1431 em Santo Afonso. Está agendada uma visita para amanhã.", fup_pendente: true, etapa_funil: "visita" },
    { created_at: "2026-02-03 18:04:36.989+00", telefone: "17996705991", nome: "Joaquim Costa", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "kitnet", valor_buscado: 0, temperatura: "frio", resumo: "Cliente está no início da pesquisa por kitnet para locação. Empresa enviou link para consulta.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:04:41.357+00", telefone: "17996763685", nome: "Lara Martins", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente iniciou conversa, mas não especificou interesse em imóveis. Empresa se colocou à disposição para ajudar.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:04:44.777+00", telefone: "17996783478", nome: "Miguel Lima", busca_imovel: true, busca_locacao: false, busca_compra: true, caracteristicas_imovel: "casas", valor_buscado: 420000, temperatura: "morno", resumo: "Cliente quer ver duas casas e pergunta sobre horário de funcionamento. Empresa confirmou que atende e não fecha para almoço.", fup_pendente: false, etapa_funil: "visita" },
    { created_at: "2026-02-03 18:04:54.434+00", telefone: "17997012822", nome: "Olívia Souza", busca_imovel: false, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "imóvel na Avenida dos Juritis, 105", valor_buscado: 0, temperatura: "frio", resumo: "A imobiliária informa que o imóvel na Avenida dos Juritis, 105, foi finalizado e pergunta se pode retornar para locação pelo mesmo valor.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:05:00.051+00", telefone: "17997062531", nome: "Pedro Lucas", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente foi informado sobre a desocupação do imóvel e questionado sobre a locação e valor, mas respondeu apenas 'Ok', sem indicar interesse de busca.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:05:05.649+00", telefone: "17997087725", nome: "Quésia Almeida", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Conversa informativa da empresa ao cliente sobre proibição de festas e barulho no condomínio, sem manifestação de interesse do cliente.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:05:16.259+00", telefone: "17997134561", nome: "Rafaela Costa", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "kitinet para alugar", valor_buscado: 700, temperatura: "quente", resumo: "O cliente demonstrou interesse em alugar uma kitinet e solicitou informações sobre visita e garantia locatícia.", fup_pendente: false, etapa_funil: "visita" },
    { created_at: "2026-02-03 18:05:30.941+00", telefone: "17997192099", nome: "Theo Martins", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente entrou em contato para esclarecer dúvidas, sem menção a busca de imóvel ou interesse.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:05:42.702+00", telefone: "17997244351", nome: "Bárbara Lima", busca_imovel: true, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "imóvel na R. Progresso, 265", valor_buscado: 0, temperatura: "morno", resumo: "Cliente Bárbara enviou documentos para análise da imobiliária referente a um imóvel na R. Progresso, 265 Coester.", fup_pendente: true, etapa_funil: "proposta" },
    { created_at: "2026-02-03 18:08:29.684+00", telefone: "18996631558", nome: "Yuri Pereira", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "salão comercial para alugar", valor_buscado: 3500, temperatura: "muito_quente", resumo: "Cliente busca alugar um salão comercial, enviou dados para simulação de seguro fiança, que foi informada.", fup_pendente: false, etapa_funil: "proposta" },
    { created_at: "2026-02-03 18:07:47.11+00", telefone: "17997658606", nome: "Sarah Rocha", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "aluguel com carência e valores graduais", valor_buscado: 2400, temperatura: "muito_quente", resumo: "Cliente aceitou proposta de aluguel com carência e valores graduais, sem inclusão do IPTU. Estão acertando detalhes finais para fechamento do contrato.", fup_pendente: false, etapa_funil: "fechamento" },
    { created_at: "2026-02-03 18:07:50.784+00", telefone: "17997712044", nome: "Vitor Souza", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente é advogada oferecendo assessoria jurídica para empresas, não demonstrando interesse em imóveis.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:07:57.87+00", telefone: "17997727590", nome: "Xavier Lima", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "casa com 3 dormitórios", valor_buscado: 2500, temperatura: "frio", resumo: "Cliente busca imóvel para alugar, mencionou casa com 3 dormitórios por R$ 2.500 mensais. Conversa está em estágio inicial.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:08:17.952+00", telefone: "17997922887", nome: "Wesley Costa", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "Imóveis para locação", valor_buscado: 0, temperatura: "frio", resumo: "Cliente solicitou catálogo de imóveis para locação. Empresa enviou link com imóveis disponíveis para locação.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:08:34.448+00", telefone: "18997180053", nome: "Zoe Martins", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Conversa relacionada a normas de convivência no apartamento, incluindo proibição de festas e barulho excessivo, sem menção a interesse em compra ou locação.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:08:39.036+00", telefone: "18997524630", nome: "Adrian Souza", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente forneceu dados da proprietária para atualização cadastral. Cliente confirmou que vai verificar qual conta bancária será usada para repasse.", fup_pendente: true, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:08:45.987+00", telefone: "18998006779", nome: "Bruna Lima", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Cliente solicitou informações sobre os pagamentos de uma locatária da qual ele é fiador. Imobiliária encaminhou para o setor financeiro.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:08:50.431+00", telefone: "19982591172", nome: "Caio Pereira", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "muito_frio", resumo: "Conversa apenas com comunicado da empresa sobre regras do condomínio, sem interesse ou busca ativa do cliente.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:08:53.64+00", telefone: "19989012748", nome: "Diana Rocha", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Início da conversa com apenas saudações e troca de cumprimentos, sem informações sobre interesse em imóvel.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:09:05.086+00", telefone: "19995639961", nome: "Elisa Costa", busca_imovel: true, busca_locacao: false, busca_compra: true, caracteristicas_imovel: "casa", valor_buscado: 350000, temperatura: "morno", resumo: "Cliente manifestou interesse em uma casa, sem fornecer detalhes adicionais. É necessário fazer follow-up para obter mais informações.", fup_pendente: true, etapa_funil: "contato" },
    { created_at: "2026-02-03 18:09:11.22+00", telefone: "21968355378", nome: "Fabio Souza", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "morno", resumo: "Cliente ainda não decidiu sobre a compra de imóvel, aguarda posição financeira para amanhã. Mencionou problema de cadastro com a Elektro.", fup_pendente: true, etapa_funil: "contato" },
    { created_at: "2026-02-03 18:09:18.553+00", telefone: "3196572446", nome: "Giovanna Lima", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "A conversa não indica busca por imóvel ou negociação. Foi apenas enviado comunicado sobre normas de convivência, proibindo festas e barulho excessivo.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:09:22.698+00", telefone: "3496932824", nome: "Hugo Martins", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "Conversa breve sem indicação de interesse em busca de imóvel ou próximos passos.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:06:58.693+00", telefone: "17997491025", nome: "Iara Pereira", busca_imovel: true, busca_locacao: false, busca_compra: true, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "morno", resumo: "O cliente demonstrou interesse em informações sobre financiamento de casa e informou que irá entrar em contato amanhã.", fup_pendente: true, etapa_funil: "contato" },
    { created_at: "2026-02-03 18:07:05.503+00", telefone: "17997527671", nome: "Jonas Souza", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "Imóvel para locação no bairro Santo Afonso", valor_buscado: 3800, temperatura: "morno", resumo: "Cliente tem interesse em imóvel para locação no bairro Santo Afonso, faixa de valor por volta de R$ 3800,00 + IPTU.", fup_pendente: true, etapa_funil: "visita" },
    { created_at: "2026-02-03 18:07:10.497+00", telefone: "17997534710", nome: "Kelly Lima", busca_imovel: true, busca_locacao: true, busca_compra: false, caracteristicas_imovel: "Imóvel para alugar em Fernandópolis", valor_buscado: 2500, temperatura: "frio", resumo: "Cliente busca imóvel para alugar em Fernandópolis na faixa de 2 mil a 3 mil reais. Empresa enviou link com opções de imóveis para aluguel.", fup_pendente: false, etapa_funil: "novo" },
    { created_at: "2026-02-03 18:07:16.715+00", telefone: "17997552213", nome: "Leandro Costa", busca_imovel: false, busca_locacao: false, busca_compra: false, caracteristicas_imovel: "", valor_buscado: 0, temperatura: "frio", resumo: "A imobiliária enviou um link de imóveis para o cliente e realizou um primeiro contato.", fup_pendente: false, etapa_funil: "novo" }
];

// Notificações mockadas
const notificationsData = [
    {
        id: 1,
        title: "Lead Quente Detectado",
        message: "Alice Martins está pronta para fechar um aluguel de R$1.200",
        type: "hot",
        time: "5 minutos atrás",
        read: false
    },
    {
        id: 2,
        title: "FUP Pendente",
        message: "Fernanda Lima aguarda resposta sobre visita ao apartamento 254",
        type: "warning",
        time: "1 hora atrás",
        read: false
    },
    {
        id: 3,
        title: "Nova Proposta",
        message: "Gustavo Lima negociando valor do aluguel para R$1.900",
        type: "info",
        time: "2 horas atrás",
        read: false
    }
];

// Exportar para uso global
window.TENANTS = TENANTS;
window.atendimentosData = atendimentosData;
window.notificationsData = notificationsData;
